
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import Footer from "./components/footer/footer";
import ProviderStore from "./components/providerStore/providerStore";



export const metadata = {
  title: "restaurant Rove",
  description: "Generated by create next app",
};
export const viewport = "width=device-width, initial-scale=1";

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <head>
        <meta charSet="UTF-8" />
      </head>
      <body
        className={`antialiased`}
      >
        <ProviderStore>
          <Navbar />
          {children}
          <Footer />
        </ProviderStore>
      </body>
    </html>
  );
}
